// THIS FILE IS GENERATED — do not edit by hand.
// Regenerate with: npm run build:grammar
// Source: board.grammar
/* eslint-disable */
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Keyword = 2,
  ComponentType = 3,
  ParamType = 4,
  ChartType = 5,
  FormatName = 6,
  HeaderOption = 7,
  Boolean = 8,
  Identifier = 9,
  String = 10,
  TripleString = 11,
  Number = 12,
  LineComment = 13

// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,dashboard:70, param:72, row:74, include:76, visible:78, metric:80, chart:82, table:84, text:86, daterange:88, select:90, number:92, toggle:94, multiselect:96, line:98, bar:100, area:102, donut:104, pie:106, scatter:108, heatmap:110, funnel:112, gauge:114, currency:116, percent:118, compact:120, datetime:122, badge:124, span:126, type:128, connection:130, true:132, false:134}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pQVQPOOOOQO'#C^'#C^OOQO'#C_'#C_OOQO'#C`'#C`OOQO'#Ca'#CaOOQO'#Cb'#CbOOQO'#Cc'#CcOOQO'#Cd'#CdOOQO'#Ce'#CeOOQO'#C}'#C}OOQO'#Cy'#CyQVQPOOOOQO-E6w-E6w",
  stateData: "$u~OpOS~OYXOZXO[XO]XO^XO_XO`XOaXObXOcXOdXOeXOfXOgXOhXOiXOjXOkXOlXOrWOsPOtPOuPOvPOwPOxQOyQOzQO{QO|RO}RO!ORO!PRO!QRO!RSO!SSO!TSO!USO!VSO!WSO!XSO!YSO!ZSO![TO!]TO!^TO!_TO!`TO!aUO!bUO!cUO!dVO!eVO~O]ZY[rY~",
  goto: "!RrPPssssssssPPPPPPPPPPPPPPPPPPPwPPP}TXOZQZOR[ZTYOZ",
  nodeNames: "⚠ Program Keyword ComponentType ParamType ChartType FormatName HeaderOption Boolean Identifier String TripleString Number LineComment { } ( ) [ ] : , = == != <= >= < >",
  maxTerm: 67,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*V~RfXY!gYZ!g]^!gpq!gqr!xrs#Tst'Pxy'hyz'm|}'r!Q!['w![!](b!^!_(g!_!`(t!`!a)R!c!})`!}#O)q#P#Q)v#R#S)`#T#o)`#o#p){#q#r*Q~!lSp~XY!gYZ!g]^!gpq!g~!{P!_!`#O~#TOh~~#WWOY#pZr#prs%ds#O#p#O#P$b#P;'S#p;'S;=`%^<%lO#p~#sWOY#pZr#prs$]s#O#p#O#P$b#P;'S#p;'S;=`%^<%lO#p~$bOY~~$eRO;'S#p;'S;=`$n;=`O#p~$qXOY#pZr#prs$]s#O#p#O#P$b#P;'S#p;'S;=`%^;=`<%l#p<%lO#p~%aP;=`<%l#p~%iPY~rs%l~%oTOr%lrs&Os;'S%l;'S;=`&y<%lO%l~&RTOr%lrs&bs;'S%l;'S;=`&y<%lO%l~&eTOr%lrs&ts;'S%l;'S;=`&y<%lO%l~&yOZ~~&|P;=`<%l%l~'US]~OY'PZ;'S'P;'S;=`'b<%lO'P~'eP;=`<%l'P~'mO`~~'rOa~~'wOe~~'|Q[~!O!P(S!Q!['w~(VP!Q![(Y~(_P[~!Q![(Y~(gOd~~(lPk~!_!`(o~(tOi~~(yPf~!_!`(|~)ROg~~)WPl~!_!`)Z~)`Oj~~)eSr~!Q![)`!c!})`#R#S)`#T#o)`~)vOb~~){Oc~~*QO^~~*VO_~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 34, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 168
})

